services:
  product-service-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: products
    ports:
      - 5433:5432
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
    driver: local